package com.eudistack.ebw.wallet.config.infrastructure.controller.dto;

import com.eudistack.ebw.wallet.config.domain.model.TenantWalletConfigDescriptor;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * Public discovery response DTO for {@code GET /.well-known/wallet-config-metadata}.
 *
 * <p>Intentionally omits the {@code key_manager} field (AD-1bis: topology reconnaissance
 * prevention). The JSON serialisation uses snake_case names as defined in the discovery
 * plane contract.
 *
 * <p>Immutable record — constructors and accessors are generated by the Java compiler.
 */
public record DiscoveryResponseDto(
        @JsonProperty("wallet_mode") String walletMode,
        @JsonProperty("natural_persons_only") boolean naturalPersonsOnly,
        @JsonProperty("supported_credentials") List<String> supportedCredentials,
        @JsonProperty("version") long version
) {

    /**
     * Maps a {@link TenantWalletConfigDescriptor} to the public discovery DTO.
     *
     * <p>{@code key_manager} is deliberately excluded — see AD-1bis in tech-design.md §3.5.
     */
    public static DiscoveryResponseDto from(TenantWalletConfigDescriptor descriptor) {
        return new DiscoveryResponseDto(
                descriptor.getWalletMode().getValue(),
                descriptor.isNaturalPersonsOnly(),
                descriptor.getSupportedCredentials(),
                descriptor.getVersion());
    }
}
