package com.eudistack.ebw.wallet.config.infrastructure.controller.dto;

import com.eudistack.ebw.wallet.config.domain.model.operational.OperationalConfigDescriptor;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.Instant;

/**
 * HTTP response body for {@code POST/PUT/GET /business-wallet/admin/wallet-operational-config}.
 *
 * <p>Security invariant (AC-2c): the {@code wrapped_dek} field and the
 * {@code column_encryption_key_arn} are intentionally excluded from the response.
 * The operator already knows the ARN (they supplied it), and the DEK ciphertext must
 * never be returned over the wire once persisted.
 *
 * <p>Serialises using snake_case {@code @JsonProperty} names, matching the request
 * body naming convention and the DB column names.
 *
 * <p>Immutable record — Jackson serialises via the accessor methods generated by the compiler.
 */
public record OperationalConfigResponseDto(
        @JsonProperty("key_manager") String keyManager,
        @JsonProperty("activation_status") String activationStatus,
        @JsonProperty("connectivity_verified_at") Instant connectivityVerifiedAt,
        @JsonProperty("is_active") boolean isActive,
        @JsonProperty("version") long version,
        @JsonProperty("updated_at") Instant updatedAt
) {

    /**
     * Maps an {@link OperationalConfigDescriptor} to the response DTO.
     *
     * <p>{@code wrapped_dek} and {@code column_encryption_key_arn} are deliberately excluded.
     * {@code connectivityVerifiedAt} is {@code null} when the descriptor carries
     * {@code Optional.empty()} (i.e. {@code activation_status = pending-spi}).
     *
     * @param descriptor the persisted descriptor; must not be null
     * @return the response DTO
     */
    public static OperationalConfigResponseDto from(OperationalConfigDescriptor descriptor) {
        return new OperationalConfigResponseDto(
                descriptor.keyManager().getValue(),
                descriptor.activationStatus().getValue(),
                descriptor.connectivityVerifiedAt().orElse(null),
                descriptor.isActive(),
                descriptor.version(),
                descriptor.updatedAt()
        );
    }
}
