spring:
  application:
    name: eudistack-core-wallet-ebw

server:
  port: 8080

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include: health, prometheus
      base-path: /
      path-mapping:
        health: health
        prometheus: prometheus
  endpoint:
    health:
      access: unrestricted
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:when-authorized}
      probes:
        enabled: true
    prometheus:
      access: unrestricted
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
