package com.eudistack.ebw.keymanager.application;

import reactor.core.publisher.Mono;

import java.util.Optional;

/**
 * Outgoing port for the hybrid sign correlation / idempotency store.
 *
 * <p>Maps a {@code correlationId} (UUID v7, generated by the EBW in {@code prepareSign}) to
 * a {@link PreparedSign} snapshot that {@code submitSignedAssertion} uses to verify the
 * client signature and assemble the {@code kb_jwt}. Entries expire automatically after TTL
 * ≤ 5 min (architecture.md §8.1).</p>
 *
 * <p>Idempotency contract:
 * <ul>
 *   <li>{@code putPending} — idempotent: a second call with the same {@code correlationId}
 *       is a no-op (network retry of {@code prepareSign}); the existing entry is preserved.</li>
 *   <li>{@code markResolved} — sets the final {@code kb_jwt} once; a second call with the
 *       same {@code correlationId} and a different {@code kbJwt} MUST throw
 *       {@link com.eudistack.ebw.keymanager.domain.exception.OnboardingStateException}
 *       (409 {@code idempotency_replay}) — handled in {@code SubmitSignedUseCase}.</li>
 * </ul>
 *
 * <p><b>Single-instance caveat:</b> the current implementation is Caffeine-backed (in-process).
 * Before enabling horizontal EBW scaling (EUDISTACK-68), this port must be backed by a
 * shared store (e.g., Redis). See Tech Debt ticket for tracking.
 *
 * <p>Spec: EUDISTACK-536 EC-03; architecture.md §8.1.</p>
 */
public interface PreparedSignStore {

    /**
     * Stores a new pending session. No-op if the same {@code correlationId} already exists.
     *
     * @param correlationId UUID v7 generated by {@code PrepareSignUseCase}
     * @param prepared      the prepared session snapshot; {@code resolvedKbJwt} must be null
     */
    Mono<Void> putPending(String correlationId, PreparedSign prepared);

    /**
     * Retrieves the session for the given {@code correlationId}, or {@link Optional#empty()}
     * if the entry has expired or was never stored.
     */
    Mono<Optional<PreparedSign>> getIfPresent(String correlationId);

    /**
     * Atomically marks the session as resolved with the given {@code kbJwt}.
     * Preserves the existing resolved value if already resolved (idempotent replay path).
     *
     * @param correlationId the correlation ID of the session to resolve
     * @param kbJwt         the compact {@code kb_jwt} produced by a successful submit
     */
    Mono<Void> markResolved(String correlationId, String kbJwt);
}
