name: pr-to-main

on:
  pull_request:
    branches:
      - main
      - 'release/v*'
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  checks: write
  pull-requests: write
  security-events: write

jobs:
  application-ci:
    uses: ./.github/workflows/reusable-pr.yml
    with:
      container_image: 'wallet-ebw-service'
      container_name: 'wallet-ebw-service'
      smoke_url: 'http://localhost:8080/business-wallet/health/readiness'
      zap_target_url: 'http://localhost:8080/business-wallet'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  license-compliance:
    uses: ./.github/workflows/reusable-license-gate.yml

  analyze:
    uses: ./.github/workflows/reusable-codeql.yml
